stages:
  - build
  - test

build:
  image: node:latest
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist

cypress_test:
  image: cypress/base:18.14.1
  stage: test
  script:
    - npm ci
    - npm run dev
    - npm install -g wait-on
    - wait-on http://localhost:5173
    - npm run cypress:run
