image: node:latest

stages:
  - build
  - test

build:
  stage: build
  script:
    - npm ci
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist

cypress_test:
  image: cypress/base:16.18.1
  stage: test
  script:
    - npm ci
    - npm install -g serve
    - npm install -g wait-on
    - serve -s dist &
    - wait-on http://localhost:3000
    - npm run cypress:run
